export const ADD_ROLL_TO_FRAME = 'ADD_ROLL';
export const NEXT_FRAME = 'NEXT_FRAME';
export const UPDATE_FRAME_LIST = 'UPDATE_FRAME_LIST';
export const ADD_FRAME_TO_LIST = 'ADD_FRAME_TO_LIST';
export const COUNT_TOTAL_SCORE = 'COUNT_TOTAL_SCORE';
export const UPDATE_RESULTS_WITH_BONUS = 'UPDATE_RESULTS_WITH_BONUS';
